server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: banking-admin-system
    
  # Database Configuration - MySQL for persistent storage
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Nethish@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Changed from 'none' to 'update' - preserves data
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: false
        hbm2ddl:
          auto: update  # Explicitly set to update
        
  # SQL Initialization - DISABLED to prevent conflicts
  sql:
    init:
      mode: never  # Changed from 'always' to 'never'
      continue-on-error: false

# JWT Configuration
jwt:
  secret: mySecretKeyForBankingAdminSystemThatShouldBeVerySecureInProduction
  expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    com.securebank: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized